# -------- Config -------- #

homeassistant:
  name: Home
  unit_system: metric
  time_zone: Europe/Berlin
  packages: !include_dir_named includes
  allowlist_external_dirs: [/config/]

default_config:
browser_mod:

# -------- Lovelace -------- #

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js?v=0.10.0
      type: module
    - url: /hacsfiles/config-template-card/config-template-card.js
      type: module
    - url: /hacsfiles/stack-in-card/stack-in-card.js
      type: module
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-hui-element/hui-element.js
      type: module
    - url: /hacsfiles/weather-card/weather-card.js
      type: module          
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/light-popup-card/light-popup-card.js
      type: module
    - url: /hacsfiles/light-entity-card/light-entity-card.js
      type: module           
    - url: /hacsfiles/battery-state-card/battery-state-card.js
      type: module
    - url: /hacsfiles/kiosk-mode/kiosk-mode.js
      type: module     
    - url: /browser_mod.js
      type: module
    - url: '/local/custom_icons.js'
      type: module
  dashboards:
    lovelace-default:
      mode: yaml
      title: Default
      filename: dashboards/default.yaml
      show_in_sidebar: false
                
# -------- Integrations -------- #

# config flow: cast, asuswrt, openweathermap, broadlink, fullykiosk

nextcloud:
  url: !secret nextcloud_url
  username: !secret nextcloud_user
  password: !secret nextcloud_password

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

synology_dsm:
  host: !secret synologydsm_host
  port: !secret synologydsm_port
  ssl: true
  verify_ssl: false
  username: !secret synologydsm_username
  password: !secret synologydsm_password

brother:
  host: !secret brother_host
  type: laser