# -------- Config -------- #

homeassistant:
  name: "127.0.0.1"
  country: DE
  latitude: !secret home_lat
  longitude: !secret home_lng
  packages: !include_dir_named includes
  allowlist_external_dirs: [ /config/ ]
  time_zone: Europe/Berlin
  unit_system: metric
  external_url: "https://home.kris.pizza"
  internal_url: "http://home-assistant:8123"

  customize:
    cover.blinds_wohnzimmer_links:
      icon: mdi:roller-shade
    cover.blinds_wohnzimmer_rechts:
      icon: mdi:roller-shade
    binary_sensor.door_sensor_arbeitszimmer_contact:
      friendly_name: Door Arbeitszimmer open
    binary_sensor.window_sensor_arbeitszimmer_contact:
      friendly_name: Window Arbeitszimmer open
    binary_sensor.window_sensor_wohnzimmer_links_contact:
      friendly_name: Window Wohnzimmer Links open
    binary_sensor.window_sensor_wohnzimmer_rechts_contact:
      friendly_name: Window Wohnzimmer Rechts open
    binary_sensor.window_sensor_kuche_contact:
      friendly_name: Window K端che open
    switch.steam_link_wohnzimmer:
      friendly_name: Steam Link
      icon: mdi:steam
    switch.dehumidifier_kuche:
      friendly_name: Dehumidifier
      icon: mdi:air-humidifier
    switch.plug_kitchen_speaker:
      friendly_name: Kitchen speaker
      icon: mdi:speaker
    switch.plug_air_purifier:
      friendly_name: Air Purifier
      icon: mdi:air-purifier
    vacuum.roborock_vacuum_a15:
      friendly_name: Marvin
    light.light_stehlampe_wohnzimmer:
      friendly_name: Stehlampe Wohnzimmer
      icon: mdi:floor-lamp
    light.light_decke_wohnzimmer:
      friendly_name: Decke Wohnzimmer
      icon: mdi:light-recessed
    light.light_bett_oben:
      friendly_name: Bett Oben
      icon: mdi:led-strip-variant
    light.light_bett_unten:
      friendly_name: Bett Unten
      icon: mdi:lamp
    light.light_ambient_bett_unten:
      friendly_name: Ambient Bett Unten
      icon: mdi:led-strip-variant
    light.light_ambient_beamer:
      friendly_name: Ambient Beamer
      icon: mdi:led-strip-variant
    light.light_ambient_stereo:
      friendly_name: Ambient Stereo
      icon: mdi:led-strip-variant
    light.light_kris_schreibtisch:
      friendly_name: Kris Desk
      icon: mdi:led-strip-variant
    light.elgato_gw24l1a03117:
      friendly_name: Kris Keylight
      icon: mdi:light-flood-down
    light.light_bathroom:
      friendly_name: Decke Badezimmer
      icon: mdi:ceiling-light
    light.light_hani_schreibtisch_ambient:
      friendly_name: Hani Desk Ambient
      icon: mdi:led-strip-variant
    light.light_stehlampe_arbeitszimmer:
      friendly_name: Stehlampe Arbeitszimmer
      icon: mdi:floor-lamp
    light.light_decke_arbeitszimmer:
      friendly_name: Decke Arbeitszimmer
      icon: mdi:light-recessed
    light.light_decke_flur:
      friendly_name: Decke Flur
      icon: mdi:ceiling-light
    light.light_arbeitslicht_kuche:
      friendly_name: Arbeitslicht K端che
      icon: mdi:led-strip-variant
    light.light_decke_kuche:
      friendly_name: Decke K端che
      icon: mdi:ceiling-light
    climate.climate_kuche:
      friendly_name: K端che
    climate.climate_wohnzimmer:
      friendly_name: Wohnzimmer
    climate.climate_arbeitszimmer:
      friendly_name: Arbeitszimmer
    binary_sensor.presence_bathroom_presence:
      friendly_name: Presence Badezimmer
      icon: mdi:shower
    binary_sensor.hallway_person_occupancy:
      friendly_name: AI person detection
      icon: mdi:cctv
    switch.light_bathroom_mirror:
      friendly_name: Badezimmer Spiegel
      icon: mdi:lightbulb-fluorescent-tube-outline

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.1.0/24

#auth_header:
#  username_header: X-authentik-username
#  # Optionally set this if you don't want to bypass the login prompt
#  # allow_bypass_login: false
#  # Optionally enable debug mode to see the headers Home-Assistant gets
#  debug: true
#
#logger:
#  default: info
#  logs:
#    custom_components.auth_header: debug

frontend:
  themes: !include_dir_merge_named themes

default_config:

# -------- Lovelace -------- #

lovelace:
  mode: yaml
  resources:

    # - used by me - #
    - url: /hacsfiles/lovelace-mushroom/mushroom.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js
      type: module
    - url: /hacsfiles/frigate-hass-card/frigate-hass-card.js
      type: module

    # - for minimalist UI - #
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/my-cards/my-cards.js
      type: module
    - url: /hacsfiles/light-entity-card/light-entity-card.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/simple-weather-card/simple-weather-card-bundle.js
      type: module
    - url: /hacsfiles/weather-radar-card/weather-radar-card.js
      type: module
    - url: /hacsfiles/vacuum-card/vacuum-card.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/lovelace-state-switch/state-switch.js
      type: module
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
