button_card_templates: !include button_card_templates.yaml

views:
  - title: Default
    path: default
    icon: mdi:home-lightbulb
    cards:
      - type: grid
        columns: 4
        square: false
        cards:
          - type: custom:button-card
            entity: switch.scene_dining
            show_name: false
          - type: custom:button-card
            entity: switch.scene_work
            show_name: false
          - type: custom:button-card
            entity: switch.scene_romantic
            show_name: false
          - type: custom:button-card
            entity: switch.scene_cinema
            show_name: false
          - type: custom:button-card
            entity: switch.scene_bath
            show_name: false
          - type: custom:button-card
            entity: switch.scene_off
            show_name: false
      - type: grid
        columns: 3
        square: true
        cards:
          - type: custom:button-card
            entity: light.stehlampe_wohnzimmer
            template:
              - light
              - icon_shade
          - type: custom:button-card
            entity: light.decke_wohnzimmer
            template:
              - light
              - icon_panel
          - type: custom:button-card
            entity: light.bett_oben
            template:
              - light
              - icon_led
          - type: custom:button-card
            entity: light.stehlampe_arbeitszimmer
            template:
              - light
              - icon_work_lamp
          - type: custom:button-card
            entity: light.decke_arbeitszimmer
            template:
              - light
              - icon_panel
          - type: custom:button-card
            entity: light.decke_flur
            template:
              - light
              - icon_ceiling
          - type: custom:button-card
            entity: light.arbeitslicht
            template:
              - light
              - icon_led    
          - type: custom:button-card
            entity: light.deckenlampe
            template:
              - light
              - icon_ceiling_double

  
