button_card_templates: !include button_card_templates.yaml

views:
  - title: Default
    path: default
    icon: mdi:home
    cards:
      - type: vertical-stack
        cards:
          - type: grid
            columns: 4
            square: false
            cards:
              - type: custom:button-card
                entity: switch.scene_dining
                show_name: false
              - type: custom:button-card
                entity: switch.scene_work
                show_name: false
              - type: custom:button-card
                entity: switch.scene_romantic
                show_name: false
              - type: custom:button-card
                entity: switch.scene_cinema
                show_name: false
              - type: custom:button-card
                entity: switch.scene_music
                show_name: false
              - type: custom:button-card
                entity: switch.scene_bath
                show_name: false
              - type: custom:button-card
                entity: switch.scene_off
                show_name: false
          - type: markdown
            content: " "
            style:
              .: |
                ha-card {
                  background-color: transparent !important;
                  box-shadow: none !important;
                }
          - type: grid
            columns: 3
            square: false
            cards:
              - type: custom:button-card
                icon: mdi:volume-minus
                tap_action:
                  action: call-service
                  service: remote.send_command
                  service_data:  
                    entity_id: remote.ir_blaster_remote
                    device: stereo
                    command: volume-down
              - type: custom:button-card
                icon: mdi:volume-off
                tap_action:
                  action: call-service
                  service: remote.send_command
                  service_data:  
                    entity_id: remote.ir_blaster_remote
                    device: stereo
                    command: mute
              - type: custom:button-card
                icon: mdi:volume-plus
                tap_action:
                  action: call-service
                  service: remote.send_command
                  service_data:  
                    entity_id: remote.ir_blaster_remote
                    device: stereo
                    command: volume-up
          - type: markdown
            content: " "
            style:
              .: |
                ha-card {
                  background-color: transparent !important;
                  box-shadow: none !important;
                }
          - type: grid
            columns: 3
            square: true
            cards:
              - type: custom:button-card
                entity: light.stehlampe_wohnzimmer
                template:
                  - light
                  - icon_shade
              - type: custom:button-card
                entity: light.decke_wohnzimmer
                template:
                  - light
                  - icon_panel
              - type: custom:button-card
                entity: light.bett_oben
                template:
                  - light
                  - icon_led
              - type: custom:button-card
                entity: light.stehlampe_arbeitszimmer
                template:
                  - light
                  - icon_work_lamp
              - type: custom:button-card
                entity: light.decke_arbeitszimmer
                template:
                  - light
                  - icon_panel
              - type: custom:button-card
                entity: light.decke_flur
                template:
                  - light
                  - icon_ceiling
              - type: custom:button-card
                entity: light.arbeitslicht
                template:
                  - light
                  - icon_led    
              - type: custom:button-card
                entity: light.deckenlampe
                template:
                  - light
                  - icon_ceiling_double

