# -------- Sensors -------- #
template:
  - sensor:
    - name: 'miner_earnings_daily'
      unit_of_measurement: 'EUR'
      state: >
        {% set iot_price_usd = states('sensor.helium_price_iot') | float %}
        {% set usd_eur_rate = states('sensor.open_exchange_rates_usd_eur') | float %}
        {% set iot_earnings = states('sensor.miner_wallet_daily') | float %}
        {% set energy_price = states('input_number.energy_price') | float %}
        {% set energy_spent = states('sensor.miner_energy_spent_daily') | float %}
        {% set earnings = (iot_price_usd * usd_eur_rate * iot_earnings) %}
        {% set cost = (energy_price * energy_spent) %}
        {{ (earnings - cost) | round(2, default=0) }}
    - name: 'miner_earnings_weekly'
      unit_of_measurement: 'EUR'
      state: >
        {% set iot_price_usd = states('sensor.helium_price_iot') | float %}
        {% set usd_eur_rate = states('sensor.open_exchange_rates_usd_eur') | float %}
        {% set iot_earnings = states('sensor.miner_wallet_weekly') | float %}
        {% set energy_price = states('input_number.energy_price') | float %}
        {% set energy_spent = states('sensor.miner_energy_spent_weekly') | float %}
        {% set earnings = (iot_price_usd * usd_eur_rate * iot_earnings) %}
        {% set cost = (energy_price * energy_spent) %}
        {{ (earnings - cost) | round(2, default=0) }}
    - name: 'miner_earnings_monthly'
      unit_of_measurement: 'EUR'
      state: >
        {% set iot_price_usd = states('sensor.helium_price_iot') | float %}
        {% set usd_eur_rate = states('sensor.open_exchange_rates_usd_eur') | float %}
        {% set iot_earnings = states('sensor.miner_wallet_monthly') | float %}
        {% set energy_price = states('input_number.energy_price') | float %}
        {% set energy_spent = states('sensor.miner_energy_spent_monthly') | float %}
        {% set earnings = (iot_price_usd * usd_eur_rate * iot_earnings) %}
        {% set cost = (energy_price * energy_spent) %}
        {{ (earnings - cost) | round(2, default=0) }}
    - name: 'miner_earnings_yearly'
      unit_of_measurement: 'EUR'
      state: >
        {% set iot_price_usd = states('sensor.helium_price_iot') | float %}
        {% set usd_eur_rate = states('sensor.open_exchange_rates_usd_eur') | float %}
        {% set iot_earnings = states('sensor.miner_wallet_yearly') | float %}
        {% set energy_price = states('input_number.energy_price') | float %}
        {% set energy_spent = states('sensor.miner_energy_spent_yearly') | float %}
        {% set earnings = (iot_price_usd * usd_eur_rate * iot_earnings) %}
        {% set cost = (energy_price * energy_spent) %}
        {{ (earnings - cost) | round(2, default=0) }}
  - binary_sensor:
    # TODO: TRVs, power sockets are missing
    - name: 'something_is_critical'
      state: > 
        {%- if is_state('binary_sensor.temperatur_humidity_kuche_critical', 'on') or is_state('binary_sensor.temperature_humidity_arbeitszimmer_critical', 'on') or is_state('binary_sensor.temperature_humidity_wohnzimmer_critical', 'on') or is_state('binary_sensor.window_sensor_kuche_critical', 'on') or is_state('binary_sensor.window_sensor_arbeitszimmer_critical', 'on') or is_state('binary_sensor.window_sensor_wohnzimmer_critical', 'on') or is_state('binary_sensor.motion_sensor_flur_critical', 'on') or is_state('binary_sensor.dimmer_wohnzimmer_critical', 'on') or is_state('binary_sensor.dimmer_arbeitszimmer_critical', 'on') or is_state('binary_sensor.dimmer_kuche_critical', 'on') or is_state('binary_sensor.button_flur_critical', 'on') or is_state('binary_sensor.dimmer_kuche_critical', 'on') or is_state('binary_sensor.internet_connected', 'off') or is_state('light.light_bett_unten', 'unavailable') or is_state('light.light_decke_arbeitszimmer', 'unavailable') or is_state('light.light_decke_kuche', 'unavailable') or is_state('light.light_decke_flur', 'unavailable') or is_state('light.light_decke_wohnzimmer', 'unavailable') or is_state('light.kris_schreibtisch', 'unavailable') or is_state('light.light_hani_schreibtisch', 'unavailable') or is_state('light.light_ambient_stereo', 'unavailable') or is_state('light.light_ambient_beamer', 'unavailable') or is_state('light.light_stehlampe_arbeitszimmer', 'unavailable') or is_state('light.light_stehlampe_wohnzimmer', 'unavailable') or is_state('light.light_arbeitslicht_kuche', 'unavailable') or is_state('light.light_bett_oben', 'unavailable') or is_state('light.light_bett_unten', 'unavailable') -%}on{%- else -%}off{%- endif -%}
    - name: 'temperatur_humidity_kuche_critical'
      state: >
        {%- if states('sensor.temperature_humidity_kuche_battery')|int(0) < 30 or states('sensor.temperature_humidity_kuche') == 'unavailable' -%}on{%- else -%}off{%- endif -%}
    - name: 'temperature_humidity_arbeitszimmer_critical'
      state: >
        {%- if states('sensor.temperature_humidity_arbeitszimmer_battery')|int(0) < 30 or states('sensor.temperature_humidity_arbeitszimmer') == 'unavailable' -%}on{%- else -%}off{%- endif -%}
    - name: 'temperature_humidity_wohnzimmer_critical'
      state: >
        {%- if states('sensor.temperature_humidity_wohnzimmer_battery')|int(0) < 30 or states('sensor.temperature_humidity_wohnzimmer') == 'unavailable' -%}on{%- else -%}off{%- endif -%}
    - name: 'window_sensor_kuche_critical'
      state: >
        {%- if states('sensor.window_sensor_kuche_battery')|int(0) < 30 or states('sensor.window_sensor_kuche') == 'unavailable' -%}on{%- else -%}off{%- endif -%}
    - name: 'window_sensor_arbeitszimmer_critical'
      state: >
        {%- if states('sensor.window_sensor_arbeitszimmer_battery')|int(0) < 30 or states('sensor.window_sensor_arbeitszimmer') == 'unavailable' -%}on{%- else -%}off{%- endif -%}
    - name: 'window_sensor_wohnzimmer_critical'
      state: >
        {%- if states('sensor.window_sensor_wohnzimmer_battery')|int(0) < 30 or states('sensor.window_sensor_wohnzimmer') == 'unavailable' -%}on{%- else -%}off{%- endif -%}
    - name: 'motion_sensor_flur_critical'
      state: >
        {%- if states('sensor.motion_sensor_flur_battery')|int(0) < 30 or states('sensor.motion_sensor_flur') == 'unavailable' -%}on{%- else -%}off{%- endif -%}
    - name: 'dimmer_arbeitszimmer_critical'
      state: >
        {%- if states('sensor.dimmer_arbeitszimmer_battery')|int(0) < 30 or states('sensor.dimmer_arbeitszimmer') == 'unavailable' -%}on{%- else -%}off{%- endif -%}
    - name: 'dimmer_wohnzimmer_critical'
      state: >
        {%- if states('sensor.dimmer_wohnzimmer_battery')|int(0) < 30 or states('sensor.dimmer_wohnzimmer') == 'unavailable' -%}on{%- else -%}off{%- endif -%}
    - name: 'dimmer_kuche_critical'
      state: >
        {%- if states('sensor.dimmer_kuche_battery')|int(0) < 30 or states('sensor.dimmer_kuche') == 'unavailable' -%}on{%- else -%}off{%- endif -%}
    - name: 'button_flur_critical'
      state: >
        {%- if states('sensor.button_flur_battery')|int(0) < 30 or states('sensor.button_flur') == 'unavailable' -%}on{%- else -%}off{%- endif -%}

# -------- Sensors -------- #
group:
  arbeitszimmer_windows:
    name: Arbeitszimmer Windows
    icon: mdi:window-open
    all: false
    entities:
      - binary_sensor.window_sensor_arbeitszimmer_contact
      - binary_sensor.door_sensor_arbeitszimmer_contact

# -------- binaries -------- #
binary_sensor:
  - platform: ping
    name: internet_connected
    host: 8.8.8.8
    scan_interval: 20
  - platform: ping
    name: dns_working
    host: denic.de
    scan_interval: 20

# -------- booleans -------- #
input_boolean:
  projector:
    name: Projector
    initial: off
  stereo:
    name: Stereo
    initial: off
  party:
    name: Party
    initial: off
  vacation:
    name: Vacation
    initial: off
  heating:
    name: Automated Heating
    icon: mdi:thermostat-auto
    initial: on

# -------- light groups -------- #
light:
  - platform: group
    name: light_group_wohnzimmer
    entities:
      - light.light_stehlampe_wohnzimmer
      - light.light_bett_oben
      - light.light_bett_unten
      - light.light_ambient_beamer
      - light.light_ambient_stereo
      - light.light_ambient_bett_unten
  - platform: group
    name: light_group_arbeitszimmer
    entities:
      - light.light_stehlampe_arbeitszimmer
      - light.light_kris_schreibtisch
      - light.light_hani_schreibtisch
  - platform: group
    name: light_group_flur
    entities:
      - light.light_decke_flur
  - platform: group
    name: light_group_kuche
    entities:
      - light.light_arbeitslicht_kuche
      - light.light_decke_kuche
  - platform: group
    name: light_group_party_color
    entities:
      - light.light_kris_schreibtisch
      - light.light_ambient_beamer
      - light.light_ambient_stereo
      - light.light_ambient_bett_unten

# -------- energy -------- #
sensor:
  - platform: integration
    source: sensor.home_server_plug_power
    name: home_server_energy_spent
    unit_prefix: k
    round: 2
  - platform: integration
    source: sensor.dehumidifier_kuche_power
    name: dehumidifier_energy_spent
    unit_prefix: k
    round: 2
  - platform: integration
    source: sensor.plug_helium_miner_power
    name: helium_miner_energy_spent
    unit_prefix: k
    round: 2
  - platform: integration
    source: sensor.steam_link_wohnzimmer_power
    name: steam_link_energy_spent
    unit_prefix: k
    round: 2

# -------- inputs -------- #
input_number:
  energy_price:
    name: Price per kwh in EUR
    initial: 0.3685
    min: 0
    max: 100
    step: 0.0001
input_select:
  monitoring_range:
    name: Monitoring range
    options:
      - day
      - week
      - month
      - year
    initial: day
    icon: mdi:calendar-clock

# -------- helium -------- #
utility_meter:
  miner_energy_spent_daily:
    source: sensor.helium_miner_energy_spent
    cycle: daily
  miner_wallet_daily:
    source: sensor.helium_hotspot_polite_butter_hippo_total_rewards
    cycle: daily
  miner_energy_spent_weekly:
    source: sensor.helium_miner_energy_spent
    cycle: weekly
  miner_wallet_weekly:
    source: sensor.helium_hotspot_polite_butter_hippo_total_rewards
    cycle: weekly
  miner_energy_spent_monthly:
    source: sensor.helium_miner_energy_spent
    cycle: monthly
  miner_wallet_monthly:
    source: sensor.helium_hotspot_polite_butter_hippo_total_rewards
    cycle: monthly
  miner_energy_spent_yearly:
    source: sensor.helium_miner_energy_spent
    cycle: yearly
  miner_wallet_yearly:
    source: sensor.helium_hotspot_polite_butter_hippo_total_rewards
    cycle: yearly
